--Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as revenue
from customer
group by gender
--Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id,purchase_amount
FROM customer
WHERE discount_applied = 'Yes'AND purchase_amount >= (SELECT AVG(purchase_amount)FROM customer);

--Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased, ROUND(AVG(review_rating::numeric),2) AS "average product rating"
from customer
group by item_purchased
order by AVG(review_rating) desc
limit 5

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type,
round(avg(purchase_amount),2)
from customer
where shipping_type in('Standard','Express')
group by shipping_type
--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status,
COUNT(customer_id)as"Total customers",
ROUND(AVG(purchase_amount),2)as avg_spend,
ROUND(SUM(purchase_amount),2)as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
       ROUND(
           SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100.0
           / COUNT(*),
           2
       ) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;
--Q7. Segment customers linto New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
SELECT
    CASE
        WHEN previous_purchases <= 10 THEN 'New'
        WHEN previous_purchases <= 30 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment,
    COUNT(*) AS customer_count
FROM customer
GROUP BY customer_segment
ORDER BY customer_count DESC;
--Q8. What are the top 3 most purchased products within each category?
with item_counts as(
select category,
item_purchased,
COUNT(customer_id)as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) DESC)as item_rank
from customer
group by category, item_purchased
)
select item_rank,  category, item_purchased, total_orders
from item_counts
where item_rank <=3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(*) AS customer_count
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;
--Q10. What is the revenue contribution of each age group
select age_group, 
SUM(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;
